import 'bootstrap/dist/css/bootstrap.css';
import { Inter } from "next/font/google";
import BootstrapClient from '@/components/BootstrapClient.js';
import "./globals.css";
import "@/assets/main.scss"


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
      <BootstrapClient />
    </html>
  );
}
